services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      MONGO_URL: mongodb://db:27017/database
    ports:
      - 80:80
    depends_on: [db]
    volumes:
      - ./components:/usr/src/app/components:ro
      - ./lib:/usr/src/app/lib:ro
      - ./models:/usr/src/app/models:ro
      - ./pages:/usr/src/app/pages:ro

  db:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 27017:27017