# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

# Want to help us make this template better? Share your feedback here: https://forms.gle/ybq9Krt8jtBL3iCk7

ARG PNPM_VERSION=12@sha256:6233cc54f782bb3a25ff26be344432354811d31358f768186d90a384a8d4ca6c

FROM ghcr.io/pnpm/pnpm:${PNPM_VERSION}

RUN pnpm runtime set node 26 -g

ENV NODE_ENV=development

WORKDIR /usr/src/app

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to pnpm's store to speed up subsequent builds.
# Leverage a bind mount to package.json and pnpm-lock.yaml to avoid having to copy them into
# this layer.
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=pnpm-lock.yaml,target=pnpm-lock.yaml \
    --mount=type=cache,target=/pnpm/store \
    pnpm install --frozen-lockfile

ENV NODE_ENV=production

# Copy the rest of the source files into the image.
COPY . .

CMD ["pnpm", "exec", "ts-node", "-T", "scripts/perform-migration.ts"]