services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.development
    environment:
      DATABASE_URL: postgresql://scavhunt:scavhunt@db:5432/scavhunt?schema=public
    ports:
      - 80:80
    depends_on: [db]
    volumes:
      - ./components:/usr/src/app/components:ro
      - ./lib:/usr/src/app/lib:ro
      - ./pages:/usr/src/app/pages:ro
      - ./prisma:/usr/src/app/prisma:ro
      - ./public:/usr/src/app/public:ro
      - ./scripts:/usr/src/app/scripts:ro

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: scavhunt
      POSTGRES_PASSWORD: scavhunt
      POSTGRES_DB: scavhunt
    ports:
      - "5434:5432"
    volumes:
      - scavhunt_pg:/var/lib/postgresql/data

volumes:
  scavhunt_pg:
